#!/usr/bin/env bash

# Read /etc/passwd line by line using a while loop
while IFS=: read -r username _ userid groupid info home shell; do
    # Extract additional information from /etc/passwd
    IFS=',' read -r _ _ _ password _ <<< "$info"
    
    # Display the story for each user
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $userid $info"
    echo
done < /etc/passwd

