#!/usr/bin/env bash

# Define the file name for the key pair and the passphrase
KEY_NAME="school"
PASSPHRASE="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b 4096 -f ~/.ssh/$KEY_NAME -N "$PASSPHRASE"

# Inform the user
echo "RSA key pair created:"
echo "Private key: ~/.ssh/$KEY_NAME"
echo "Public key: ~/.ssh/${KEY_NAME}.pub"
